### ISSUE TITLE
Wikileaks.org - fake news?

### ISSUE THREAD

**Issue by StevenBlack** [marktron/fakenews#1]
Hi Mark,

I see these [two wikileaks entries](https://github.com/marktron/fakenews/blob/master/fakenews#L326-L327).

Overkill?

**Comment by marktron** [comment]
@StevenBlack - those were accidentally left in from my personal blocklist and not something I feel 100% confident I should be foisting on everyone :)

Did a review of the rest of the file again and feel good about it. Thanks for the catch!

**Comment by kirkins** [comment]
:see_no_evil: Open your eyes

If wikileaks shows us anything it's that mainstream media and national actors have been pushers of propaganda and misinformation both in the past and in the present.

Your project projects a narrative contrary to reality. It's a narrative which states the root of misinformation is grass roots websites. The reality is much different and you fail to address the real problems of our time.

Who cares about some super small websites making money off click bait when our own government pays mainstream news papers to spread propaganda.

https://en.wikipedia.org/wiki/Operation_Mockingbird
