### ISSUE TITLE
How did rt.com get added?

### ISSUE THREAD

**Issue by coldwizard** [marktron/fakenews#10]
RT should not be in this list https://github.com/marktron/fakenews/blob/master/fakenews#L601
It's also worth mentioning that Ruptly TV is a valid news source.

I see this has already been covered in a previous issue, and duramato's concern was not addressed:

> Certain North American news agencies are also very politically biased, enticing a political view/agenda, it's a known fact. But they are not on the list from what I can see.
A Wikipedia page touching the subject https://en.m.wikipedia.org/wiki/Media_bias_in_the_United_States

Yes, of course RT is biased. So is every other large news corporation in the United States. So shouldn't they be on the list too? That would include at the very least:
- foxnews.com
- cnn.com
- washingtonpost.com

By including RT in the list, you are sending a message of censorship. I like most of the other entries, but if you choose to leave RT in it, the entire list is invalidated. **It now serves the corporate interests of the United States government**.

Which is fine, it's not my repository to manage. You are free to promote Western viewpoints through censorship if you so choose, in which case changing the name of the repository would be considerate.

On a side note, the news article cited in issue #7 has a disclaimer at the bottom:

> This is an opinion piece. The views expressed in this article are those of just the author.

**Comment by marktron** [comment]
@coldwizard, while in my mind there is a clear difference between news outlets that display political bias and sites that are actively used as tools of disinformation by state actors (e.g. RT), it's impossible to create a ruleset that works for everyone. Feel free fork this repo and determine what sites fit your personal criteria and use that.
