### ISSUE TITLE
Remove dailywire.com from the list

### ISSUE THREAD

**Issue by ryanrodemoyer** [marktron/fakenews#12]
Hello, can you remove dailywire.com from the block list? This is a reputable news site. Thanks!

**Comment by giantslor** [comment]
No, it's not a reputable news site. See https://mediabiasfactcheck.com/the-daily-wire/

**Comment by ryanrodemoyer** [comment]
Based on that link, you could say the same thing about CNN as their aggregate result of factual reporting is mixed. The only difference between say, The Daily Wire and CNN/MSNBC is that TDW leans right and CNN/MSNBC lean left. IMO the political agenda of a media organization does not dictate whether it does or does not constitute fake news.

https://mediabiasfactcheck.com/cnn
https://mediabiasfactcheck.com/msnbc

**Comment by giantslor** [comment]
CNN has biases among individual hosts and commentators, not a site-wide overt political agenda as The Daily Wire has. CNN has been around for decades and has established a reputation as a top source for hard news. Daily Wire has been around for two years and its reputation, such as it is, is that of a purveyor of hard-right slanted articles (I hesitate to call them "news.") Also, many of CNN's supposed inaccuracies are a result of live commentary by various commentators, most of them on the right, as you can see by a cursory glance at Politifact's page on CNN.

The Daily Wire may not rise to the level of fake news, but it definitely isn't reputable like CNN.

**Comment by ryanrodemoyer** [comment]
>The Daily Wire may not rise to the level of fake news

I guess that's the point of this issue and subsequent fix; The Daily Wire
is not fake news therefore does not belong on a fake news block list.

Happy Holidays!

**Comment by giantslor** [comment]
I was mainly disputing the idea that it's a reputable site.
