### ISSUE TITLE
Possible source/light reading

### ISSUE THREAD

**Issue by ScriptTiger** [marktron/fakenews#14]
Hey, @marktron! I stumbled upon this and thought you might want to have a look and read through some of their data:

B.S. Detector:
https://github.com/bs-detector/bs-detector

Their actual data in json format with nice "type" category tags:
https://github.com/bs-detector/bs-detector/blob/dev/ext/data/data.json

And then I believe a good chunk of that data comes in turn from the Open Sources folks:
https://github.com/OpenSourcesGroup

Maybe you could even collaborate with them :)

**Comment by marktron** [comment]
Sorry, didn't mean to reference this issue in that last commit, but this is a great comment. Thanks for sharing these resources @ScriptTiger. I'm going to look into these projects some more.
