### ISSUE TITLE
Liveleak.com ??

### ISSUE THREAD

**Issue by r7l** [marktron/fakenews#15]
I was adding this list in hope to not be bothered or spammed by real bad fake news sites. But then i found Liveleak blocked on my computer and when investigating, it was because i've added this fake news filter. I don't know what kind of news agency Liveleak would be. To me it always just was a another Youtube like site.

There are allot of sites on this list, i don't want to be bothered with. But i've seen videos with Liveleak logos shown on the centrist, left or right leaning news outlets as well as state TV or anywhere else. Why not add Youtube as well? It has fake news all over the place.

I don't mind or care you remove this or not. I will simply remove this list as this seems not to work. There are a couple more entries i've found on it that would not go through as real fake news for me as well.

**Comment by marktron** [comment]
Thanks @r7l, the majority of content I've seen from LiveLeak has been conspirational in nature, but agree that it's not necessarily worse than YouTube. I've removed it from the blacklist.
