### ISSUE TITLE
Some of these sites aren't quite fake news machines...(and some omissions/other thoughts)

### ISSUE THREAD

**Issue by isiahmeadows** [marktron/fakenews#16]
Just to clear this up now so it's clear my bias isn't super *for* these sites, I'm left of center, leaning libertarian, but I also try pretty hard to avoid the filter bubble\* to be aware of opposing views and potential BS I find elsewhere (even normally reputable sites [aren't](https://www.theblaze.com/news/2017/04/18/huffington-post-forced-to-issue-retraction-after-they-get-trolled-by-fake-person) [always](https://www.washingtonpost.com/news/worldviews/wp/2017/11/15/why-i-wrote-fake-news-for-the-washington-post/?utm_term=.d7786e521ee9) [perfect](https://www.huffingtonpost.com/entry/media-complicity-is-key-t_b_13423850.html)). I personally don't frequent any of these sites, but not because they're fake news.

- The Blaze is probably the conservative equivalent of pre-Trump CNN in both reliability and how far it leans. Although it's mainly run by a single person, and it does get a bit sensationalist on occasion, it does *not* attempt to spread known falsehoods, and to its credit, it has made it a point to call [conservatives](https://www.theblaze.com/news/2017/05/23/i-retracted-nothing-sean-hannity-defiant-after-fox-news-pulls-this-story) out just as quickly as [liberals](https://www.theblaze.com/news/2017/12/08/cnn-is-getting-torched-for-correcting-another-trump-story-heres-who-theyre-blaming).
- [LGBTQ Nation](www.lgbtqnation.com) is pretty left-leaning and tends to show its bias very well, but it is [not a fake news site](https://mediabiasfactcheck.com/lgbtq-nation/), and [it does have an entire category dedicated to pointing out such content](https://www.lgbtqnation.com/tag/fake-news/).
- [Washington Examiner](http://www.washingtonexaminer.com/) is right leaning (they're somewhere between right-center and right) and openly embrace it, but [they aren't known for making false claims](https://mediabiasfactcheck.com/washington-examiner/). It's definitely tabloid in style, making no attempt to hide it, but it's probably among the least bad of the conservative tabloids, and [even FactCheck.org notes in this list](https://www.factcheck.org/2017/07/websites-post-fake-satirical-stories/) that it's considered legitimate, drawing a distinction for clarity between it and "The Examiner", a fake news site. (Or, TL;DR: it's no Daily Caller.)

Also, I do feel you probably missed a few sites:

- Fox News. If you asked me 10 years ago, I would've put it where The Blaze is now, but it started moving on to occasionally [publishing overt falsehoods](https://www.thedailybeast.com/fox-news-mainstreams-conspiracy-theory-about-parkland-students), [getting into lawsuits over false reporting](https://apnews.com/20f2b652432f473a9c45a891072192d6), among other things. It's something worth revisiting a few years down the road to see whether they change back, since they seem to be waking up to their problem at least somewhat (like [climate change](http://www.foxnews.com/us/2017/09/06/why-irma-is-so-strong-and-other-questions-about-hurricanes.html) post-[Hannity](https://www.theatlantic.com/politics/archive/2017/05/sean-hannity/528144/)).
- [Goop](https://goop.com/) - it's been [repeatedly called out](https://www.vox.com/science-and-health/2017/7/19/15988180/gwyneth-paltrow-goop-jade-egg-debunkers) for its pseudoscience claims on wellness, [even managing to win dubious awards over it](http://www.iflscience.com/health-and-medicine/gwyneth-paltrows-goop-wins-award-for-worst-pseudoscience-of-the-year/). Oh, and for the icing on the cake? [They sell the same crap Infowars does...](https://qz.com/1010684/all-the-wellness-products-american-love-to-buy-are-sold-on-both-infowars-and-goop/)
- [AlterNet](http://www.alternet.org/) has found its way to [this moderate conservative hoax list](http://www.fortliberty.org/hoax-sites.html) for similar reasons [Breitbart](https://mediabiasfactcheck.com/breitbart/) and [Fox News](https://mediabiasfactcheck.com/fox-news/) have been flagged by a few liberal lists, as its reporting on conservative matters [isn't always accurate](https://www.snopes.com/cory-booker-jared-kushner/). [Their quality](https://mediabiasfactcheck.com/alternet/) is probably on par with those two, although without their level of big funding polish. I've seen it sometimes cited by [otherwise credible sites](https://www.huffingtonpost.com/entry/alabamas-chemical-endange_b_8193196.html) on the left, at a similar frequency to Fox News on the right.

And finally, a few other small notes:

- Found some duplicates: [1](https://github.com/marktron/fakenews/blob/master/fakenews#L227-L228), [2](https://github.com/marktron/fakenews/blob/master/fakenews#L353-L354), [3](https://github.com/marktron/fakenews/blob/master/fakenews#L373-L374)
- Note that it might be worth considering, when you go to categorize, it's probably worth keeping a separate category for sources that are highly biased towards a particular nation-state or other powerful group:
    - Russia Today/RT (this one's obvious). It's not super reliable, but it can be at least moderately informative if you're interested in Russian politics (even though it's obviously not the most reliable).
    - Al Jazeera is [run by Qatar](https://en.wikipedia.org/wiki/Al_Jazeera), and is generally unreliable for anything related to the Middle East beyond war reporting (Qatar tends to butt heads over there).
    - Fox News is basically run by Republican establishment, and that has been the case for decades.
- It's also worth considering that some sites aren't quite cut and dry obvious, like [The Anti-Media](http://theantimedia.org/), the [Free Thought Project](http://thefreethoughtproject.com/), and [Investment Watch Blog](http://investmentwatchblog.com/). All three of those, for example, [are](https://mediabiasfactcheck.com/the-anti-media/) [solidly](https://mediabiasfactcheck.com/free-thought-project/) [conspiracy](https://mediabiasfactcheck.com/the-anti-media/), but they do at least *attempt* to do their homework, and they *do* occasionally report some real news (especially the last one) and have been cited occasionally by otherwise reliable news sources, so they can't be dismissed on their face. All three have a clear bias, however (liberal, libertarian, and conservative, respectfully).
- Also, on an unrelated note, you might find a few more fake news sites [here](http://ufotheater.com/ufo-channel-reviews/ufo-black-list/) - it's from a site that goes out of its way to try to debunk as many UFO hoaxes as possible, and they've found a *lot*.

-----

\* Of course, this is easier said than done, which makes search engines like DuckDuckGo invaluable.

**Comment by mva1985** [comment]
imho you may wanna double check ijr.com

for more information check here
ijr.com/about

**Comment by isiahmeadows** [comment]
@mva1985 (BTW, you may want to find third-party sources to back that up. Nobody with a critical eye should take any site's statement of being factual at face value.) I'll note that IJR is solidly right, to the point it is known to attack liberal sites on occasion, but it's not known for fake news, and [has suspended people for doing that internally](https://www.snopes.com/news/2017/03/21/ijr-obama-conspiracy-theory/).

**Comment by marktron** [comment]
Thanks @isiahmeadows and @mva1985 - I've removed the duplicates and some of the other sites mentioned. Sites like RT/ Al Jazeera / Fox News are tricky, and really straddle the line of what I feel comfortable blocking wholesale.
