### ISSUE TITLE
A list of fake/satire "news" sites from probably most well established major media factchecker in Sweden.

### ISSUE THREAD

**Issue by b9AcE** [marktron/fakenews#19]
This is a list of fake/satire "news" sites warned against by "viralgranskaren" (~"the viral scrutinizer ") at the global major media paper franchise Metro International's original Swedish edition.
Probably the most well established mainstream factchecker/debunker in Sweden.
Each site listed has a description and references previous reports of fake "news" or satire articles that were propagated as real news online to such an extent it was considered "viral".
Unfortunately it is in Swedish, but careful auto-translation should circumvent that problem.
Also not recently updated, but still worth checking for suggestions.
https://www.metro.se/artikel/viralgranskarens-varningslista-xr

**Comment by b9AcE** [comment]
Well that's unfortunate.
It took so long for this suggestion to get its first action, that the previously major newspaper had time to be shut down and it now seems the domain has been seized by domain-squatters or something.
Here's https://web.archive.org/web/20181230155542/https://www.metro.se/artikel/viralgranskarens-varningslista-xr an archived copy of the actual article @marktron, in case you didn't have time to see it before it went away.

**Comment by marktron** [comment]
Thanks @b9AcE, didn't think to check web archive. Much of the list was already on the list, but I've added the new ones.

**Comment by b9AcE** [comment]
Thanks, @marktron!
