### ISSUE TITLE
fakenewswatch.com doesn't seem to be a news website, fake or otherwise

### ISSUE THREAD

**Issue by AmperAndSand** [marktron/fakenews#2]
fakenewswatch.com seems to be a site that lists links to sites that it deems to be fake news sites. AFAIK, it does not contain any news at all - fake or otherwise. Has this site been known to post fake news? I'm thinking it might have been mistakenly added to the list.

**Comment by marktron** [comment]
Thanks for the catch, I believe that was added accidentally.
