### ISSUE TITLE
Re-add Raw Story to the blocklist

### ISSUE THREAD

**Issue by infinitytec** [marktron/fakenews#24]
People do not trust it.
https://www.sitejabber.com/reviews/rawstory.com
![image](https://user-images.githubusercontent.com/13670462/57576090-e5377000-741d-11e9-8653-91ee8a041ee1.png)

**Comment by spirillen** [comment]
Hi guys, I've been following the threads around here for `rawstory.com` but for what i understand from the snippet about, the only reason you would like to block this, is you disagree with them as you're politically stands are to the right?

For what i understand they are not "fake"(Trump) news but they are selling there stories with a left wing twist, but not in a false way, is that correct observed?

**Comment by infinitytec** [comment]
Could it be bias? Perhaps, but the articles are very much clickbait regardless. And I would say that the twist put on them is enough to warrant them as fake. For example, Raw Story had participated in sharing the lies about the Covington school kids.
