### ISSUE TITLE
Please consider un-blocking corbettreport

### ISSUE THREAD

**Issue by jcalfee** [marktron/fakenews#25]
Please consider un-blocking https://www.corbettreport.com .. This is one of the most reputable well researched and professional reporting site I know of.  Please investigate.

Sites like Corbett Report are self-funded and speak their mind.  These corporations go out of their way to attack small people like the Corbett Report.  Just look into James Corbett and I think it will become obvious..

This is what we are up against.  These companies make a massive effort to mix up real news with fake news to confuse us all.  They can't be too obvious.  The goal is met when they can censor truth.  They are smart, they mix it up to make it confusing.

![image](https://user-images.githubusercontent.com/204121/59077819-c2c03780-88a1-11e9-9e57-8eb425bcb721.png)

**Comment by ciolt** [comment]
[“the worst part about the exposure of Jeffrey Epstein’s child sex trafficking and high-level blackmail operation is that it bolsters conspiracy theories about child sex trafficking and elite corruption. Newsflash: they’re trying to gaslight you. Don’t fall for it for a second.”](https://www.corbettreport.com/the-worst-part-of-the-epstein-case-propagandawatch/)

**This site is fake news.** It's propelling a meritless theory that the Epstein case is a "conspiracy theory" which is so far from fact that it's an uninformed opinion.

**Comment by ciolt** [comment]
I advise you to stay away from sites that exist *deliberately and specifically* to misinform and provoke outrage - under the guise of “taking the red pill”. That includes sites like Corbett Report. @jcalfee

**Comment by jcalfee** [comment]
You mis-quoted .. It says: "According to the **dinosaur media**, the worst part about the exposure of Jeffrey Epstein’s child sex trafficking and high-level blackmail operation is that it bolsters conspiracy theories about child sex trafficking and elite corruption. Newsflash: they’re trying to gaslight you. Don’t fall for it for a second." .. I added the bold.

**Comment by jcalfee** [comment]
Trust me on this one, James is a good guy..  I"m always screening for dis-information myself.  James' point is more complex.  He links mis-direction in the dinosaur media to a technique called "gas lighting."  Your going to have to watch that one so see what he is saying.

**Comment by marktron** [comment]
Thanks for the input @jcalfee and @ciolt - James Corbett is a noted [conspiracy theorist](https://www.corbettreport.com/911-a-conspiracy-theory/), and after reviewing his site again much of his content does look like misinformation in my judgement, and is consistent with other sources on this list.

My recommendation is to whitelist the site in your personal blocklists.

**Comment by jcalfee** [comment]
Thanks @marktron .. Please give an example..

**Comment by jcalfee** [comment]
@ciolt you look confused.  ;) .. If your investigating something a specific example is needed.  Name calling is not evidence.  We need something we can look into to determine if it is trustworthy or credible or otherwise..  Are you blocking people because they use the world "conspiracy" or because they investigate "conspiracy"?  If so, that is not fake news, that is simply blocking people that investigate crimes.

If you were a criminal, would you want to be investigated?  No, of course not.  Then it would make since to try discredit those that investigated your bad deeds?

I choose James for a reason.  He is pretty good at sighting his sources.  This is why I'm asking what about 911 that he is reporting is "fakenews"?

**Comment by ciolt** [comment]
I think someone missed the mark about why this list exists 🙄

**Comment by jcalfee** [comment]
> This is a small attempt to limit my exposure to sites that fall under the umbrella of “fake news.” It blocks sites that willfully and regularly spread **clickbait**, **hoaxes**, **propaganda** and **disinformation**.

So, which one does corbettreport.com?  Spoiler alert, the next thing I'm going to ask for is an example.  

You mis-quoted James above but never re-visited this..  You picked a good video for the example though.  Did you realize you read and mis-quoted the material to mean the exact opposite of what was being said in the report?

Thanks for your time in looking at this.  I realize this thread is getting long.  I hope we realize this applies to the big picture.
