### ISSUE TITLE
please add these german Fake-news/Clickbait/Hate-Pages

### ISSUE THREAD

**Issue by ghost** [marktron/fakenews#29]
please add

afd.de
asylterror.com
blog.halle-leaks.de
contra-magazin.com
crimekalender.wordpress.com
de.news-front.info
de.sputniknews.com
denken-macht-frei.info
deutsch.rt.com
deutsche-stimme.de
deutsche-wirtschafts-nachrichten.de
diepresse.com
dortmundecho.org
einwanderungskritik.de
epochtimes.de
freiezeiten.net
gloria.tv
halle-leaks.de
hartgeld.com
impfen-nein-danke.de
journalistenwatch.com
kopp-report.de
kulturstudio.info
kulturstudio.wordpress.com
michael-mannheimer.net
news-front.info
noch.info
npd-mv.de
politikstube.com
politikversagen.net
pressefreiheit24.wordpress.com
rapefugees.net
schluesselkindblog.com
sputniknews.com
theeuropean.de
truth24.net
unzensuriert.de
volksstimme.de
wgvdl.com
www.afd.de
www.brd-schwindel.org
www.contra-magazin.com
www.denken-macht-frei.info
www.dortmundecho.org
www.epochtimes.de
www.freiezeiten.net
www.journalistenwatch.com
www.npd-mv.de
www.politikversagen.net
www.rapefugees.net
www.theeuropean.de
www.truth24.net
www.unzensuriert.de
www.unzensuriert.at
www.volksstimme.de

as part of the fakenews list
Thank you.

**Comment by Akamaru** [comment]
@ChrisMausKS please do not just copy, without saying that it is not your list

**Comment by ChrisMausKS** [comment]
@Akamaru please excuse my fault. I'm new to Github and didn't want do something wrong with your list.

**Comment by spirillen** [comment]
Hi @ChrisMausKS 
`afd.de` is a fully legit political party in Germany, who also got a significant number of votes at the last election.

It's OK to disagree in political matters, but adding them as "Fake news" is wrong and undemocratic action that would put this list into the "untruest wordy sources"...

Another Issue on you submission is the comment on each domain as in ex

```
afd.de ; Political right wing
example.com ; Misleading Articles
example.net ; Religious site endorsing suicide bombers
```

Just my 2 cents input

**Comment by idnovic** [comment]
deutsch.rt.com

I think russia today is a "good" news source. Well at least you can not put them with the other obviously bad news sites. They at least make real news.
