### ISSUE TITLE
removing "www" won't block rt.com subdomains

### ISSUE THREAD

**Issue by daywalk3r666** [marktron/fakenews#38]
i think it must be blocked individually.

![Screenshot_20201026-071628_Firefox_Beta](https://user-images.githubusercontent.com/15938117/97141893-e9656380-175f-11eb-83db-9417ce1d06bc.png)
![Screenshot_20201026-071503_AdAway](https://user-images.githubusercontent.com/15938117/97141907-ee2a1780-175f-11eb-994c-446f1c8402da.png)

**Comment by marktron** [comment]
Thanks @daywalk3r666, that was a mindless mistake on my part. It's corrected now.
