### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lightswitch05** [marktron/fakenews#39]
I just wanted to let you know that your fake news site blocked a news website someone linked me to. I was confused why it was blocked and started reading up on it, turns out it was one of those '[pink slim](https://www.cjr.org/analysis/as-election-looms-a-network-of-mysterious-pink-slime-local-news-outlets-nearly-triples-in-size.php)' websites. I would have never known if it hadn't been blocked. Anyways, can never be too cautious about 'news' sources. Thanks!

**Comment by marktron** [comment]
Thanks for the kind words, @lightswitch05. Like you mentioned, the research done by Columbia's Tow Center for Digital Journalism deserves the real credit for uncovering this tactic. Happy (and safe) browsing!
