### ISSUE TITLE
Reporting fake news site: aljazeera-channel.com 

### ISSUE THREAD

**Issue by AmperAndSand** [marktron/fakenews#4]
Reporting fake news site: http://aljazeera-channel.com/

Seems to be masquerading as the official Al Jazeera website: http://www.aljazeera.com/

Their [About Us](url=http://aljazeera-channel.com/about-us/) page says nearly nothing about their organization, or info about the article authors:

>ALJAZEERA -CHANNEL is an online channel dispensing up to date AND  reliable news from around the world, 24 hours a day. Giving you latest updates, breaking and developing news from each and every corner of the globe.

**Comment by marktron** [comment]
Thanks @AmperAndSand.
