### ISSUE TITLE
sciencealert.com is fake news?

### ISSUE THREAD

**Issue by davimack** [marktron/fakenews#5]
I'll admit it's rather pop-sci rather than anything terribly deep, but I haven't found it to be inaccurate or anything.  They do link out to real (academic) sources.  You might want to consider where you got that into your list.

**Comment by meinhimmel** [comment]
It's not fake. If you're using StevenBlack's unified host thing for it, place it in your whitelist file.

**Comment by davimack** [comment]
I switched to a flavor of Steven Black's hosts which did not include this list, because this list is a bit dodgy, apparently.  Not sure, but when real sites get rolled into something, I'll pass on it.

**Comment by marktron** [comment]
@davimack Thanks for the catch, this has been removed.
