### ISSUE TITLE
RT, Russia Today added by mistake?

### ISSUE THREAD

**Issue by duramato** [marktron/fakenews#7]
I see that RT is on the list https://github.com/marktron/fakenews/blob/master/fakenews#L601
Is this by mistake? it isn't a fake news reporter.

**Comment by MrTimscampi** [comment]
It's a state-run news agency, so it's kind of questionable.  
They're usually very biased in their reporting, especially if the US or the west as a whole is concerned.

IMHO, it falls into the "propaganda" part of the list.

**Comment by duramato** [comment]
Certain North American news agencies are also very politically biased, enticing a political view/agenda, it's a known fact. But they are not on the list from what I can see.
A Wikipedia page touching the subject https://en.m.wikipedia.org/wiki/Media_bias_in_the_United_States

Also, so from what you are saying, any state-run news agencies should be on the list? Per your words
> It's a state-run news agency, so it's kind of questionable

**Comment by marktron** [comment]
Being state-run doesn't immediately qualify an outlet for inclusion, but RT, in particular, has a history of publishing certifiably false news items that promote Russia's objectives. (cf. https://www.mediaite.com/online/rt-is-literally-russian-propaganda-why-does-anybody-take-it-seriously/)
